# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.SmallIntegerField()),
                ('congressional_district', models.SmallIntegerField()),
            ],
        ),
    ]
