# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongressMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('stance', models.CharField(max_length=1)),
                ('district', models.IntegerField()),
                ('party', models.CharField(max_length=15)),
                ('incumbent', models.CharField(max_length=3)),
                ('url', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('congressional_district', models.IntegerField()),
            ],
        ),
    ]
