# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='congressional_district',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
